import mongoose from 'mongoose';
import fs from 'fs';
import path from 'path';
const __dirname = path.resolve();

const InitiativesSchema = new mongoose.Schema({
    _id: [mongoose.Schema.Types.Mixed],
    segNo: String,
    title: String,
    status: String,
    type: String,
    leader: String,
    leaderInternet: String,
    sponsor: [String],
    sponsorInternet: [String],
    executiveChampion: [String],
    executiveChampionInternet: [String],
    executiveChampionReason: [String],
    associatedBusinessUnit: String,
    associatedBusinessUnitOther: String,
    patentInterest: Boolean,
    focusArea: String,
    affiliateName: [String],
    startDate: {
      type: Date,
      default: null
    },
    endDate: {
      type: Date,
      default: null
    },
    industryName: String,
    description: String,
    problemStatement: String,
    outcome: String,
    finalOutcome: String,
    SEOTitle: String,
    SEODescription: String,
    SEOKeywords: String,
    coleaders: [String],
    coleadersInternet: [String],
    participants: [String],
    participantsInternet: [String],
    contributors: [String],
    contributorsInternet: [String],    
    ERBReviewerInternet: [String],
    blogURL: String,
    slackURL: String,
    boxURL: String,
    githubURL: String,
    muralURL: String, connectionsURL: String,
    otherCollaborationURL: String,
    mainCollaborationURL: String,
    draftDate: {
      type: Date,
      default: null
    },
    submittedDate: Date,
    approvalMessage: String,
    approvedDate: Date,
    approvedBy: String,
    closeValue: String,
    requestClousureDate: {
      type: Date,
      default: null
    },
    closedDate: {
      type: Date,
      default: null
    },
    closedBy: String,
    requestPublicationDate: {
      type: Date,
      default: null
    },
    publicationSourceURL: String,
    approvedPublicationDate: {
      type: Date,
      default: null
    },
    ERBApproved: String,
    acknowledge: String,
    reportURL: [String],
    reportNo: String,
    finalPublicationDate: {
      type: Date,
      default: null
    },
    finalPublicationBoxURL: String,
    publicationConfidential: String,
    publicationCategory: String,
    publicationDescription: String,
    publicationContributors: [String],
    legacyParticipantType: String,
    legacyAutoApprove: String,
    legacyValue: String,
    lastUpdateDate: Date,
    openCallsForParticipation: Number,
    excludeInCi: Boolean,
    participantsRating: [String],
    ERBReviewerRating: [String],
    affiliateTypeChecked: Boolean,
    isAffiliateFocalApproved: Boolean,
    affType: String,
    lastChangedBy: [String],
    sponsorRegion: String,
    rating: Number,
    ratingComments: String,
    adminComments: String,
    isSprclose: String,
    pubreq: String,
    sponsorMessage: String,
    closedByName: String,
    endDateUpdatedCounter: Number,
    lastBPCheckDate: Date,
    publicBoxURL: String,
    publicBoxFolderId: String,
    boxURL_creating: Boolean,
    publicBoxURL_creating: Boolean,
    showcaseApproved: Boolean,
    showcaseComments: String,
    allowUnlimitedParticipants: String,
    submittedReminder: Boolean
}, { timestamps: true });
 
const Initiative = mongoose.model("Initiative", InitiativesSchema, "Initiative");

const MONGODB_URI = 'mongodb://ibm_cloud_8f598e46_c2c5_4132_8fe5_1d4f43918104:2f98fcbec36881ce903ae4bc0a7da0a26ec07af93ab05d83b1bddb0c6d50f17b@5d985e8e-03c0-4729-bee8-943b20e728e5-0.bn2a0fgd0tu045vmv2i0.databases.appdomain.cloud:31812,5d985e8e-03c0-4729-bee8-943b20e728e5-1.bn2a0fgd0tu045vmv2i0.databases.appdomain.cloud:31812/aotdb-dev?authSource=admin&replicaSet=replset';
const DBNAME = 'aotdb-dev';

(async () => {
    try {
        const options = {
          useNewUrlParser: true,
          useUnifiedTopology: true,
          sslCA: fs.readFileSync(`${__dirname}/cert.pem`),
          ssl: true,
          autoIndex: false
        }
        mongoose.connect(MONGODB_URI, options);
        console.log(`Connected to MongoDB [ ${DBNAME} ] succesfully...`);
  
        // CODE HERE
        const names = [	
            "cghoward@us.ibm.com",
            "pallavi.s@in.ibm.com",
            "darije.ramljak@hr.ibm.com",
            "AGRAWALS@de.ibm.com",
            "anavlop@mx1.ibm.com",
            "Anjana.Ananth@ibm.com",
            "clwhite@us.ibm.com",
            "cristina.moise@ro.ibm.com",
            "deepajain@in.ibm.com",
            "DSAYED@eg.ibm.com",
            "emiliano_pacelli@it.ibm.com",
            "jcomard@us.ibm.com",
            "Joseph.Washington@ibm.com",
            "michael.hofmeister@de.ibm.com",
            "NISHITO@jp.ibm.com",
            "ROIK@de.ibm.com",
            "vanimi@in.ibm.com",
            "florin.manaila@de.ibm.com",
            "preethi.mohan@in.ibm.com",
            "lfli@us.ibm.com",
            "sandeep.patil@in.ibm.com",
            "arao@us.ibm.com",
            "ashwini.ramani@in.ibm.com",
            "caryn@us.ibm.com",
            "cstefanita@ibm.com",
            "E30395@jp.ibm.com",
            "efarr@us.ibm.com",
            "ellie.najewicz@ibm.com",
            "emijiang@uk.ibm.com",
            "Erika.Agostinelli1@ibm.com",
            "eysha@us.ibm.com",
            "fghods@ca.ibm.com",
            "jennalau@ca.ibm.com",
            "joseluis.teja@es.ibm.com",
            "jsanusi@uk.ibm.com",
            "JuJin.An@ibm.com",
            "katharina@uk.ibm.com",
            "kdhinds@us.ibm.com",
            "kkervin@us.ibm.com",
            "larson1@us.ibm.com",
            "lindsay.herbert@uk.ibm.com",
            "lmdaniel@us.ibm.com",
            "Malgorzata.Zimon@uk.ibm.com",
            "MEGUMII@jp.ibm.com",
            "mirella.batista@ibm.com",
            "mithula.m@in.ibm.com",
            "nschwart@us.ibm.com",
            "saijagan@in.ibm.com",
            "SATOKO@jp.ibm.com",
            "spansari@in.ibm.com",
            "vidula@us.ibm.com",
            "ysantos@us.ibm.com",
            "acarrieri@uk.ibm.com",
            "adel@eg.ibm.com",
            "adrienne_mcgrory@uk.ibm.com",
            "ailbheca@ie.ibm.com",
            "ana_rivera@es.ibm.com",
            "andrew.white@uk.ibm.com",
            "anupama.murthi@ibm.com",
            "asilva@us.ibm.com",
            "Azusa.Takatsuna1@ibm.com",
            "Bahareh.Atoufi@ibm.com",
            "ceron@ibm.com",
            "chrism1@us.ibm.com",
            "diana.gergeanu@ro.ibm.com",
            "emb@us.ibm.com",
            "FANGZHU@jp.ibm.com",
            "freemanl@us.ibm.com",
            "fsbarros@us.ibm.com",
            "fscook@us.ibm.com",
            "gbonilla@us.ibm.com",
            "GEORGINAJONES@uk.ibm.com",
            "Gerald.Trotman@ibm.com",
            "gpadilla@mx1.ibm.com",
            "grainne.dolan@ae.ibm.com",
            "hollywri@au1.ibm.com",
            "jandre@br.ibm.com",
            "kakate@us.ibm.com",
            "kna@us.ibm.com",
            "lailafettah@nl.ibm.com",
            "lichtenau@de.ibm.com",
            "LouiseWebb@uk.ibm.com",
            "luis.munoz@us.ibm.com",
            "maialy@eg.ibm.com",
            "markjgeorge@uk.ibm.com",
            "micawhit@uk.ibm.com",
            "mihwa@us.ibm.com",
            "MYMZK@jp.ibm.com",
            "NARASAKI@jp.ibm.com",
            "olivier.planson@fr.ibm.com",
            "puzza@us.ibm.com",
            "ramavadl@in.ibm.com",
            "rjbrenn@us.ibm.com",
            "setarehm@us.ibm.com",
            "sharon.fortune@us.ibm.com",
            "simaoliu@us.ibm.com",
            "sinnocenti@it.ibm.com",
            "Sonja.Gresser@de.ibm.com",
            "vani@us.ibm.com",
            "vradhik@in.ibm.com",
            "vsandhya@in.ibm.com",
            "wsf1@us.ibm.com",
            "yichong@us.ibm.com",
            "erpalmer@us.ibm.com",
            "giraldo@us.ibm.com",
            "a_ortizdeuriarte@es.ibm.com",
            "ajay.chebbi@in.ibm.com",
            "Anna.Shugol@ibm.com",
            "Anne.Jobmann@ibm.com",
            "anupamaj@ibm.com",
            "aslihan.yilmaz@de.ibm.com",
            "Aya.Tokura@ibm.com",
            "bchaitra@in.ibm.com",
            "biancaz@br.ibm.com",
            "btrombl@us.ibm.com",
            "calynch@us.ibm.com",
            "caolan@cn.ibm.com",
            "carl.mayer@de.ibm.com",
            "catherine_moxey@uk.ibm.com",
            "ceaguilera@us.ibm.com",
            "charletg@us.ibm.com",
            "chermosi@us.ibm.com",
            "Cindy.Sun@ca.ibm.com",
            "coralie.jonvel@fr.ibm.com",
            "Dale.Lane@uk.ibm.com",
            "dikonoor@in.ibm.com",
            "djoeantony@in.ibm.com",
            "dlewis@us.ibm.com",
            "dominique.lacassagne@fr.ibm.com",
            "elowery@us.ibm.com",
            "erkolsto@us.ibm.com",
            "fguiraud@fr.ibm.com",
            "harini@us.ibm.com",
            "huxd@cn.ibm.com",
            "IGYUCEER@uk.ibm.com",
            "ingo.dressler@de.ibm.com",
            "isabelarnold@ibm.com",
            "jamil.spain@us.ibm.com",
            "jdivya@in.ibm.com",
            "jmulsow@us.ibm.com",
            "Jorge.L.Diaz@ibm.com",
            "jorgedr@us.ibm.com",
            "jose.manuel.pose.rivadulla@es.ibm.com",
            "jpark@ie.ibm.com",
            "jrosser@us.ibm.com",
            "kmcmill@us.ibm.com",
            "kruse-schomaker@de.ibm.com",
            "lalowe@us.ibm.com",
            "Lan.Luo11@ibm.com",
            "leri@mx1.ibm.com",
            "liher.elgezabal@es.ibm.com",
            "litingxa@cn.ibm.com",
            "lloyddean@us.ibm.com",
            "Lucia.larise.Stavarache1@ibm.com",
            "lvuong@us.ibm.com",
            "mamathakv@in.ibm.com",
            "maria.borbones@es.ibm.com",
            "mbyers@us.ibm.com",
            "mehtar@us.ibm.com",
            "mestrada@us.ibm.com",
            "mferwerda@nl.ibm.com",
            "murphysh@us.ibm.com",
            "MYHO@jp.ibm.com",
            "nsaulni@us.ibm.com",
            "Paulina.Wieckowska@pl.ibm.com",
            "pdesai@us.ibm.com",
            "pizzano@us.ibm.com",
            "prajaktak@in.ibm.com",
            "priti.patil@in.ibm.com",
            "Priyadarshini.R.Kolwalkar@ibm.com",
            "queenazh@cn.ibm.com",
            "rishika.kedia@in.ibm.com",
            "rosariou@us.ibm.com",
            "samacken@us.ibm.com",
            "Sarah.Kefayati@ibm.com",
            "scorreia@ca.ibm.com",
            "senagar3@in.ibm.com",
            "SFUMIKO@jp.ibm.com",
            "shahani@us.ibm.com",
            "shuangyu@cn.ibm.com",
            "shugupta@us.ibm.com",
            "SIMA@il.ibm.com",
            "Siobhan.Nicholson1@ibm.com",
            "skamesw@us.ibm.com",
            "skundu22@in.ibm.com",
            "Smriti.Talwar@ie.ibm.com",
            "tamara.tatian@uk.ibm.com",
            "tuukka.vartiainen@fi.ibm.com",
            "viruete@mx1.ibm.com",
            "xqin@us.ibm.com",
            "Xuemin.Fang@ibm.com",
            "jdejesus@us.ibm.com",
            "dangeville.n@fr.ibm.com",
            "mariam.azimi@us.ibm.com",
            "pskhadke@us.ibm.com",
            "ricardo.olivieri@us.ibm.com",
            "SultanSA@sa.ibm.com"
        ];
        let data = "";
        let iter=0
        for (const name of names) {
            console.log(`${name} - ${iter} of ${names.length}`)
            const initiatives = await Initiative.find({$and: [{startDate: {$gt : new Date("2018-12-31")}},{status: {$nin:["Draft", "Submitted", "Deleted","Rejected"]}},{excludeInCI: false},{$or:[{leaderInternet: { $regex: name, $options: "i"}}, {participantsInternet: { $regex: name, $options: "i"}},{coleaderInternet: { $regex: name, $options: "i"}}]}]})
            .select({title: 1, focusArea:1})
            .lean()
            .exec();
            for (const initiative of initiatives) {
                data += `"${name}","${initiative.title}","https://aotweb.dal1a.cirrus.ibm.com/initiative/${initiative._id}","${initiative.focusArea}"\n`
            }
            iter++;
        }
        fs.writeFileSync('pathways.csv', data);
        process.exit(1);
      } catch (err) {
        console.log(err.message);
        process.exit(1);
      }
})();